# Generated by Django 4.0 on 2023-12-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_questiontag_remove_question_tags_delete_questiontags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'default_related_name': 'question'},
        ),
    ]
