# Generated by Django 4.0 on 2023-12-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_profile_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='login',
            new_name='nickname',
        ),
    ]
