# Generated by Django 4.0 on 2023-11-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_questiontags_rename_tag_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='all', max_length=255),
        ),
    ]
