# Generated by Django 4.0 on 2023-11-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_likequestion_user_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontags',
            name='question_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.question'),
        ),
        migrations.AddField(
            model_name='questiontags',
            name='tag_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tag'),
        ),
    ]
